### ISSUE TITLE
Credentials leaked

### ISSUE THREAD

**Issue by i-umairkhan** [ahsanabbasi36/QuranAppBackend#2]
Mongodb credentials can be seen in `.env` file. Make sure you hide them.

**Comment by ahsanabbasi36** [comment]
Done Done
Thanks for reminding my friend from chakwal deya.

**Comment by i-umairkhan** [comment]
Credentials can still be seen in **first commit history**. Try to remove them form thier as well.

**Comment by ahsanabbasi36** [comment]
addressed. Thanks once again

**Comment by ahsanabbasi36** [comment]
A short reminder !!
All the problem was caused because i forget to put the dot before env in the gitignore file!
